---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nxing-deployment
    minion: banana
  name: nginx-deployment
  namespace: application
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    # type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: 'nginx:1.21.0'
          name: server
          resources:
            limits:
              cpu: '0.5'
              memory: '256Mi'
            requests:
              cpu: '0.3'
              memory: '64Mi'
